name       : python-qtconsole
version    : 5.3.1
release    : 16
source     :
    - https://github.com/jupyter/qtconsole/archive/refs/tags/5.3.1.tar.gz : ab169377f4dd40ccb0627fdfe5c472686f07980a7fa28005042cac2bce82fd95
homepage   : https://github.com/jupyter/qtconsole
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Qt Console
description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich media output, session export, and more. The Qtconsole is a very lightweight application that largely feels like a terminal, but provides a number of enhancements only possible in a GUI, such as inline figures, proper multiline editing with syntax highlighting, graphical calltips, and more.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-ipykernel
    - python-ipython_genutils
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
