name       : python-qtconsole
version    : 5.1.0
release    : 10
source     :
    - https://github.com/jupyter/qtconsole/archive/refs/tags/5.1.0.tar.gz : 350786f1ec874e7e3fe19c715c592ad3401ad794b0e8763be38b74be4e6cd969
homepage   : https://github.com/jupyter/qtconsole
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Qt Console
description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich media output, session export, and more.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-ipykernel
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
