name       : python-qtconsole
version    : 5.0.3
release    : 9
source     :
    - https://github.com/jupyter/qtconsole/archive/5.0.3.tar.gz : 50de506815f9d9a17b3e99c5e88fe2aaff72097d900a9e56f38c5f8ba02590b0
homepage   : https://github.com/jupyter/qtconsole
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Qt Console
description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich media output, session export, and more.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-ipykernel
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
