name       : python-qtconsole
version    : 4.4.4
release    : 3
source     :
    - https://github.com/jupyter/qtconsole/archive/4.4.4.tar.gz : 87d02948cca41e35fda2d80dfcfcf809257256c7872b71e851f223fbe67e3b5e
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Qt Console
description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich media output, session export, and more.
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - pygments
    - python3-qt5
    - python-ipykernel
    - python-ipython_genutils
    - python-jupyter_client
    - python-jupyter_core
    - python-qt5
    - python-traitlets
build      : |
    %python3_setup
    %python_setup
install    : |
    %python3_install
    for _f in $installdir/usr/bin/*; do
        mv -v $_f ${_f}3
    done
    %python_install
