name       : python-qtconsole
version    : 5.2.2
release    : 13
source     :
    - https://github.com/jupyter/qtconsole/archive/refs/tags/5.2.2.tar.gz : d5cfb4bb2f812301ae75bd856c2bd0adcc52a935567ea72cc8037c7e1972a58a
homepage   : https://github.com/jupyter/qtconsole
license    : BSD-3-Clause
component  : programming.python
summary    : Jupyter Qt Console
description: |
    A rich Qt-based console for working with Jupyter kernels, supporting rich media output, session export, and more. The Qtconsole is a very lightweight application that largely feels like a terminal, but provides a number of enhancements only possible in a GUI, such as inline figures, proper multiline editing with syntax highlighting, graphical calltips, and more.
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - pygments
    - python-ipykernel
    - python-qtpy
build      : |
    %python3_setup
install    : |
    %python3_install
